language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
- 3.5
before_install:
- pip install -U pip setuptools wheel tox-travis
- pip install twine
- pip install -r ./requirements_dev.txt
branches:
  only:
  - master
  - "/^v?\\d(\\.\\d+)+$/"
script:
- python setup.py sdist
- python setup.py bdist_wheel
- twine check dist/*
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  user: __token__
  password:
    secure: oyMCnzgxWJ7h/9cygdsXYPVWJUnMlG84w7MBPoDMvuHni5lLOiJY5DlM+oRKcXJHNEsT4h2Vo9OquOlINL9Sdug+PgAcs5gH5Wq3uSWc/5BnhW4q10ShYrpTDC89YuN0uy8zA5F3vwyDkHtj1Xv2tl1JfG45RRDX5x1yXt+xIFu3FtT2Qz6hwXjGaJebSXrxolKX0HSCWzjO7NsSZPeDt/tTHc5cFKdWt5gbuz3Z7+mw2Boh5pyafGohzfMbkuSkjGX971qSleYJqvdxfD6yxa927yp1jDazXW7xh52ixpr8h4bpuYLx2oAGlBaVA9muKlexHwypIPgumsW4on7IEVm83U704a9E8V5gD87zeYyuHhkmlSmJ7mBAsATcWQRqOba84f0niaXtC23Lp4BEC19ZX1lU7zxox62qRr/CHeJbx14Dp2e+ib/8eH8Mt3jwL4po2h6A3MVugeeASm7m+HjzjjzTA7wPLnOyw4TZcmzRw1x0Cd2/HNxZ0y7+xXUO/6ia9oiSC8vQA9GOsvHrzx235DuI/IGL2FdaAONs0BJsOuRTSlb6+OMY00UF6IlZbDM3TI8K+mSyI2IEoKqoAdTCxXQRmmVuv6BL+wrRf0KmyoCfRQ51J28sTJnwDcRzf9dxG+Ft+kyuKju9Z+6pvwXm1EgThVEwNpyjHv82p2c=
  on:
    repo: dldevinc/django-spectrum
    condition: "$TRAVIS_PYTHON_VERSION = 3.8"
    tags: true
